#!/bin/bash

# Sensible bash defaults
[ -f ~/.bash/sensible.bash ] && source ~/.bash/sensible.bash

umask 022

# set vim as *the* editor
export VISUAL=vim
export EDITOR=vim

# set pager display ANSI colors
export PAGER="less -FRSX"

# SOLARIZED HEX     16/8 TERMCOL  XTERM/HEX   L*A*B      RGB         HSB
# --------- ------- ---- -------  ----------- ---------- ----------- -----------
# base03    #002b36  8/4 brblack  234 #1c1c1c 15 -12 -12   0  43  54 193 100  21
# base02    #073642  0/4 black    235 #262626 20 -12 -12   7  54  66 192  90  26
# base01    #586e75 10/7 brgreen  240 #585858 45 -07 -07  88 110 117 194  25  46
# base00    #657b83 11/7 bryellow 241 #626262 50 -07 -07 101 123 131 195  23  51
# base0     #839496 12/6 brblue   244 #808080 60 -06 -03 131 148 150 186  13  59
# base1     #93a1a1 14/4 brcyan   245 #8a8a8a 65 -05 -02 147 161 161 180   9  63
# base2     #eee8d5  7/7 white    254 #e4e4e4 92 -00  10 238 232 213  44  11  93
# base3     #fdf6e3 15/7 brwhite  230 #ffffd7 97  00  10 253 246 227  44  10  99
# yellow    #b58900  3/3 yellow   136 #af8700 60  10  65 181 137   0  45 100  71
# orange    #cb4b16  9/3 brred    166 #d75f00 50  50  55 203  75  22  18  89  80
# red       #d30102  1/1 red      124 #af0000 45  70  60 211   1   2   0  99  83
# magenta   #d33682  5/5 magenta  125 #af005f 50  65 -05 211  54 130 331  74  83
# violet    #6c71c4 13/5 brmagenta 61 #5f5faf 50  15 -45 108 113 196 237  45  77
# blue      #268bd2  4/4 blue      33 #0087ff 55 -10 -45  38 139 210 205  82  82
# cyan      #2aa198  6/6 cyan      37 #00afaf 60 -35 -05  42 161 152 175  74  63
# green     #859900  2/2 green     64 #5f8700 60 -20  65 133 153   0  68 100  60

# Base16 Shell
# BASE16_SHELL="$HOME/.bash/base16-shell/base16-eighties.dark.sh"

if [ -n "$BASE16_SHELL" ]; then
  source "$BASE16_SHELL"
fi

if [ -n "$TERM" ]; then
  dircolors=$HOME/.dircolors-$(tput colors)
  dircolors=$HOME/.dircolors.ansi-universal

  if command -v dircolors >/dev/null 2>&1; then
    if [[ -f $dircolors ]]; then
      eval "$(dircolors -b $dircolors)"
    else
      eval "$(dircolors)"
    fi
  fi
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
cygwin|xterm-color)
    PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    ;;
*256color*)
    PS1='\[\e[38;5;8m\]\h \[\e[34m\]\w\[\e[0m\]$(~/.bin/git-cwd-info)\[\e[0m\]\n\[\e[35m\]$\[\e[0m\] '
    ;;
*)
    PS1='\u@\h:\w\$ '
    ;;
esac


# ╺┳╸┏┳┓╻ ╻╻ ╻
#  ┃ ┃┃┃┃ ┃┏╋┛
#  ╹ ╹ ╹┗━┛╹ ╹
#
# Display tmux session name
if [[ -n "$TMUX" ]] ; then
  session_name=$(tmux list-pane -F '#S' | head -1)
  cat_cmd="cat"

  if hash lolcat 2>/dev/null; then
    cat_cmd="lolcat"
  fi

  hash toilet 2>/dev/null; pretty_print=$?

  if [[ $pretty_print -eq 0 ]]; then
    toilet -f future "$session_name" | "$cat_cmd"
  else
    printf "\nTMUX Session: %s\n" "$session_name" | "$cat_cmd"
  fi
fi

# Add project's bin/ to PATH after rbenv init.
export PATH=".git/safe/../../bin:${PATH}"

# Colored man pages: http://linuxtidbits.wordpress.com/2009/03/23/less-colors-for-man-pages/
# Less Colors for Man Pages
export LESS_TERMCAP_mb=$'\E[01;31m'            # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;4m'        # begin bold
export LESS_TERMCAP_me=$'\E[0m'                # end mode
export LESS_TERMCAP_se=$'\E[0m'                # end standout-mode
export LESS_TERMCAP_so=$'\E[48;5;3m\E[38;5;0m' # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'                # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;5m'        # begin underline

export MAKEPASSWD_CHARS="!\"#$%&\`()*,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_abcdefghijklmnopqrstuvwxyz{|}~"

# vim: ft=sh
